# -*- coding: utf-8 -*-
"""Consumer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1stFyg-OarJTcEyW_yluqknDokzdYGW64
"""

from kafka import KafkaConsumer
from json import loads
import json

consumer=KafkaConsumer('youtube', 
                       bootstrap_servers=['localhost:9092'],
                       api_version=(0,10)
                       #, consumer_timeout_ms=1000
                       )

for message in consumer:
  #print(message)
  print(message.value)